cr_subcr_options = {
    "Гуртожиток": [
        "умови проживання (чистота, ремонт)",
        "кількість місць (велика?)",
        "розташування (відстань до корпусів, транспортна доступність)", 
        "вартість"
    ],
    "Якість навчання": [
        "кваліфікація викладачів (наукові ступені, публікації)",
        "ефективність методів навчання"
    ],
    "Репутація університету на ринку праці": [
        "відсоток працевлаштованих випускників", 
        "середня зарплата після випуску",
        "взаємодія з компаніями"
    ],
    "Міжнародні можливості": [
        "програми обміну (Erasmus+, подвійний диплом)",
        "кількість партнерських університетів",
        "доступність програм для студентів"
    ]
}


# топ-60 университетов Украины, топ-60 Европы, топ-60 Америки, топ-50 Азии и если уника нет, то есть возможность добавить свой
uni_options = {
    "Україна": [
        "Київський національний університет імені Тараса Шевченка",
        "Національний університет «Львівська політехніка»",
        "Національний технічний університет України «Київський політехнічний інститут імені Ігоря Сікорського»",
        "Сумський державний університет",
        "Львівський національний університет імені Івана Франка",
        "Харківський національний університет імені В.Н. Каразіна",
        "Національний університет біоресурсів і природокористування України",
        "Карпатський національний університет імені Василя Стефаника",
        "Національний технічний університет «Харківський політехнічний інститут»",
        "Одеський національний університет імені І.І. Мечникова",
        "Національний технічний університет «Дніпровська політехніка»",
        "Чернівецький національний університет імені Юрія Федьковича",
        "Дніпровський національний університет імені Олеся Гончара",
        "Національний університет «Києво-Могилянська академія»",
        "Ужгородський національний університет",
        "Міжрегіональна Академія управління персоналом",
        "Національний медичний університет імені О.О. Богомольця",
        "Національний університет водного господарства та природокористування",
        "Західноукраїнський національний університет",
        "Український державний університет науки і технологій",
        "Вінницький національний технічний університет",
        "Київський національний університет будівництва і архітектури",
        "Волинський національний університет імені Лесі Українки",
        "Харківський національний університет радіоелектроніки",
        "Національний аерокосмічний університет ім. М. Є. Жуковського «Харківський авіаційний інститут»",
        "Івано-Франківський національний технічний університет нафти і газу",
        "Тернопільський національний медичний університет імені І.Я. Горбачевського",
        "Київський національний економічний університет імені Вадима Гетьмана",
        "Національний університет «Полтавська політехніка імені Юрія Кондратюка»",
        "Національний університет харчових технологій",
        "Харківський національний медичний університет",
        "Київський столичний університет імені Бориса Грінченка",
        "Державний університет «Житомирська політехніка»",
        "Національний університет «Одеська політехніка»",
        "Київський національний університет технологій та дизайну",
        "Тернопільський національний технічний університет імені Івана Пулюя",
        "Державний торговельно-економічний університет",
        "Харківський національний університет міського господарства імені О.М. Бекетова",
        "Кременчуцький національний університет імені Михайла Остроградського",
        "Сумський національний аграрний університет",
        "Вінницький національний медичний університет ім. М.І. Пирогова",
        "Тернопільський національний педагогічний університет імені Володимира Гнатюка",
        "Запорізький національний університет",
        "Харківський національний автомобільно-дорожній університет",
        "Буковинський державний медичний університет",
        "Львівський національний медичний університет імені Данила Галицького",
        "Черкаський національний університет імені Богдана Хмельницького",
        "Національний університет кораблебудування імені адмірала Макарова",
        "Хмельницький національний університет",
        "Дніпровський державний медичний університет",
        "Полтавський державний медичний університет",
        "Український державний університет залізничного транспорту",
        "Національний університет цивільного захисту України",
        "Національний університет «Запорізька політехніка»",
        "Східноукраїнський національний університет імені Володимира Даля",
        "Криворізький національний університет",
        "Харківський національний економічний університет імені Семена Кузнеця",
        "Донецький національний університет імені Василя Стуса",
        "Дрогобицький державний педагогічний університет імені Івана Франка",
        "Державний біотехнологічний університет"
    ],

    "Європа": [
        "University of Oxford",
        "University of Cambridge",
        "Imperial College London",
        "ETH Zurich",
        "UCL",
        "Technical University of Munich",
        "University of Edinburgh",
        "LMU Munich",
        "École Polytechnique Fédérale de Lausanne",
        "King’s College London",
        "KU Leuven",
        "Paris Sciences et Lettres – PSL Research University Paris",
        "Universität Heidelberg",
        "London School of Economics and Political Science",
        "Karolinska Institute",
        "University of Manchester",
        "Delft University of Technology",
        "University of Amsterdam",
        "Wageningen University & Research",
        "Institut Polytechnique de Paris",
        "Université Paris-Saclay",
        "Leiden University",
        "Sorbonne University",
        "University of Bristol",
        "University of Groningen",
        "University of Glasgow",
        "Humboldt University of Berlin",
        "University of Copenhagen",
        "Charité - Universitätsmedizin Berlin",
        "RWTH Aachen University",
        "University of Bonn",
        "Lund University",
        "University of Vienna",
        "KTH Royal Institute of Technology",
        "University of Birmingham",
        "University of Tübingen",
        "Aarhus University",
        "University of Helsinki",
        "Erasmus University Rotterdam",
        "University of Bern",
        "University of Sheffield",
        "Free University of Berlin",
        "University of Oslo",
        "Ghent University",
        "University of Leeds",
        "University of Basel",
        "Technical University of Denmark",
        "University of Göttingen",
        "University of Warwick",
        "University of Hamburg",
        "University of Lausanne",
        "Uppsala University",
        "University of Southampton",
        "University of Bologna",
        "Maastricht University",
        "Queen Mary University of London",
        "Scuola Normale Superiore di Pisa",
        "University of Freiburg",
        "University of Liverpool"
    ],

    "Сполучені Штати Америки": [
        "Massachusetts Institute of Technology",
        "Princeton University",
        "Harvard University",
        "Stanford University",
        "California Institute of Technology",
        "University of California, Berkeley",
        "Yale University",
        "University of Pennsylvania",
        "The University of Chicago",
        "Johns Hopkins University",
        "Cornell University",
        "University of California, Los Angeles",
        "Columbia University",
        "University of Michigan-Ann Arbor",
        "Carnegie Mellon University",
        "University of Washington",
        "Duke University",
        "Northwestern University",
        "New York University",
        "Georgia Institute of Technology",
        "University of Illinois at Urbana-Champaign",
        "University of California, San Diego",
        "University of Texas at Austin",
        "University of Wisconsin-Madison",
        "University of California, Davis",
        "Brown University",
        "Washington University in St Louis",
        "University of California, Santa Barbara",
        "University of Southern California",
        "Boston University",
        "University of North Carolina at Chapel Hill",
        "Purdue University West Lafayette",
        "University of Minnesota",
        "Vanderbilt University",
        "University of California, Irvine",
        "Emory University",
        "Rice University",
        "Michigan State University",
        "Ohio State University",
        "Penn State",
        "University of Massachusetts",
        "University of Maryland, College Park",
        "University of Rochester",
        "University of Florida",
        "University of Arizona",
        "Case Western Reserve University",
        "Texas A&M University",
        "University of Pittsburgh",
        "University of Colorado Boulder",
        "University of Virginia (Main campus)",
        "Dartmouth College",
        "University of California, Santa Cruz",
        "Tufts University",
        "University of Notre Dame",
        "Indiana University",
        "Arizona State University (Tempe)",
        "Georgetown University",
        "George Washington University",
        "Northeastern University, US",
        "University of Illinois Chicago",
        "University of Miami",
        "University of Utah",
        "Boston College",
        "University of Hawai’i at Mānoa",
        "Virginia Polytechnic Institute and State University",
        "Florida State University"
    ],

    "Азія": [
        "Tsinghua University",
        "Peking University",
        "National University of Singapore",
        "Nanyang Technological University, Singapore",
        "The University of Tokyo",
        "University of Hong Kong",
        "Fudan University",
        "Zhejiang University",
        "The Chinese University of Hong Kong",
        "Shanghai Jiao Tong University",
        "University of Science and Technology of China",
        "The Hong Kong University of Science and Technology",
        "Kyoto University",
        "Nanjing University",
        "Seoul National University",
        "City University of Hong Kong",
        "Korea Advanced Institute of Science and Technology (KAIST)",
        "The Hong Kong Polytechnic University",
        "Sungkyunkwan University (SKKU)",
        "Yonsei University (Seoul campus)",
        "Tohoku University",
        "Tongji University",
        "Harbin Institute of Technology",
        "Pohang University of Science and Technology (POSTECH)",
        "Wuhan University",
        "Beijing Normal University",
        "Korea University",
        "The University of Osaka",
        "Huazhong University of Science and Technology",
        "National Taiwan University (NTU)",
        "King Fahd University of Petroleum and Minerals",
        "Tianjin University",
        "Tokyo Institute of Technology",
        "University of Macau",
        "Sichuan University",
        "Southern University of Science and Technology (SUSTech)",
        "Khalifa University",
        "Indian Institute of Science",
        "Ulsan National Institute of Science and Technology (UNIST)",
        "Beijing Institute of Technology",
        "Xi’an Jiaotong University",
        "Tel Aviv University",
        "Hanyang University",
        "Universiti Teknologi Petronas",
        "Beihang University",
        "Kyung Hee University",
        "Sun Yat-sen University",
        "Nagoya University",
        "South China University of Technology",
        "Hong Kong Baptist University",
        "Northwestern Polytechnical University",
        "Sejong University",
        "Southeast University",
        "Qatar University",
        "United Arab Emirates University",
        "East China Normal University",
        "Macau University of Science and Technology",
        "Nankai University",
        "Southern Medical University",
        "Hunan University",
        "King Saud University"
    ]
}
